### PR TITLE
Two small issues

### PR DESCRIPTION
**Pull request by tlc**
1) In some paths, restic_options['arguments'] is set to a list, in others a string.  This caused an error
when arguments: was a string larger than one byte.  (Do a dry run to see.)

2) The other change enables an error when a config file is specified, but doesn't exist or is not readable.

### CODE REVIEW

**Comment by nils-werner** [comment]
The second issue I understand. Can you explain the first one, and give some examples so I can reproduce the issue?

**Comment by tlc** [comment]
This is the example config from the README, with "arguments: ~" modified.

```
$ cat config2
# these are the options for any `crestic home` command
[home]
repo: sftp:your_server:my_computer.restic
password-file: ~/.config/restic/password

# these are the options for the `crestic home backup` command
# `arguments` are positional arguments that are appended at the end of the
# commandline. Restic expects the list of directories here.
[home.backup]
exclude-file: ~/.config/restic/excludes
# arguments: ~
arguments: /home/foo
$ env CRESTIC_CONFIG_FILE=config2 CRESTIC_DRYRUN=1 python ./crestic.py home backup
restic backup --repo sftp:your_server:my_computer.restic --password-file ~/.config/restic/password --exclude-file ~/.config/restic/excludes / h o m e / f o o
```

Note '/ h o m e / f o o' with spaces at the end of the line.  It's because *in this case* restic_arguments is a string not a list.
```
      argstring += restic_arguments
```
When it comes from `python_args.arguments`, it's a list.  When it comes from `restic_options['arguments']`, it's a string.  

My change converts it to a list.  The string might have had quoted bits ("filenames with spaces"), so I parse with shlex.split() instead of str.split().  But that removes the quotes -- they're not needed in list form.  Since you go back to string form below `" ".join(argstring)`, I re-quoted them with shlex.quote().

**Comment by nils-werner** [comment]
What version are you using?

**Comment by tlc** [comment]
Your latest.

**Comment by nils-werner** [comment]
Can you check the latest version in `master` and see if it fixes your issue?

**Comment by tlc** [comment]
It does, thanks.

**Pull request closed without merging**
